# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Living Code Blog
email: taushsampley@gmail.com
author: Taush Sampley
description: >- # this means to ignore newlines until "baseurl:"
  This is the place where I update my progress cleaning up old incomplete
  projects. Hopefully some new projects as well.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://taushsampley.com" # the base hostname & protocol for your site, e.g. http://example.com
# permalink: /:categories/:year/:month/:day/:title:output_ext
twitter_username: SampleyTaush
github_username:  TSampley
rss: Feed
google_analytics: G-0S1RMMPFVZ
google_ads: ca-pub-2640513385126692
paypal_link: https://www.paypal.com/donate/?business=LET9YEHVRUVEL&no_recurring=0&item_name=Creating+Free%2C+Open-Source+Software+%28FOSS%29+to+disempower+our+various+tech-lord+monopolies.&currency_code=USD
show_excerpts: true

defaults:
  -
    scope:
      path: ""
      # type: "posts" "pages" "drafts" # or any site collection
    values:
      author: Taush Sampley
      # excerpt_separator: \n

collections:
  demos:
    output: true

# Minima data format override
minima:
  date_format: "%Y-%m-%d"

# Sass settings
sass:
  style: compressed

# Build settings
markdown: kramdown

theme: minima

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  # Shell
  - commands
  # Ruby
  - Gemfile
  - Gemfile.lock
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
  # Node
  - node_modules
  # NPM
  - package-lock.json
  - package.json
  # Intermediate
  # - html # apparently used during generation phase
